export const BOOKING_API_BASE_URL = 'http://127.0.0.1:3300';
export const SAVE_BOOKING_API_ROUTE = `${BOOKING_API_BASE_URL}/booking`;
export const GET_BOOKING_API_ROUTE = SAVE_BOOKING_API_ROUTE;
export const REMOVE_BOOKING_API_ROUTE = SAVE_BOOKING_API_ROUTE;
export const UPDATE_BOOKING_API_ROUTE = SAVE_BOOKING_API_ROUTE;